### ISSUE TITLE
Messages received from redis are sent to Discord

### ISSUE THREAD

**Issue by Folas1337** [AzisabaNetwork/RyuZUPluginChat#148]
Imagine you are using the following RPC config.yml on 2 servers:
```
[unimportant for this...]
discord:
  enable: true
  token: "[redacted]"
  vc-command-lunachat-channel: "voicechat"
  connections:
    global:
      discord-channel-id: [redacted]
      discord-input: true
      channel:
        enable: false
        matches:
            - "Global"
```
To prevent Discord messages appearing in Minecraft twice you can set only one server to connections.global.discord-input: true and the other one to false.

Now it appears that if I send a message on Minecraft it gets sent to Redis as well as Discord. The second Minecraft server receives it through redis and then also sends it through Discord, making the same message appear twice.

I think it would be better to not have messages which were already received through redis be sent to Discord again as I don't see any use case where that would make sense.

To give you an understanding why I'm interested in this: I have a separate Discord bot for each server, all sending global messages to the same channel and that way I can tell what Minecraft server a message originated from, by looking at the bot that sent the message. Unfortunately I can currently not do that and have to forward all global messages through one bot, also making it a single point of failure.

I'd greatly appreciate if this were looked into :)
