### ISSUE TITLE
指定した範囲のチャットのみDiscordと繋ぐ機能

### ISSUE THREAD

**Issue by siloneco** [AzisabaNetwork/RyuZUPluginChat#26]
グローバルチャンネルでの発言をDiscordの指定したチャンネルと繋ぎたい

**Comment by siloneco** [comment]
タイトル変更  
```yml
discord:
  enable: true
  token: hogehoge
  connections:
    voicechat:
      no-discord-input: false
      global:
        enable: false
      channel:
        enable: true
        matches:
          - "voicechat"
      private:
        enable: false
    admin:
      no-discord-input: true
      global:
        enable: true
      channel:
        enable: true
#       matches: # 全指定の場合無くても可
#         - "*"
      private:
        enable: true
```
みたいな書き方をして、柔軟な設定ができるようにしたい
